FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /
COPY ./app /app
COPY ./requirements.txt /

RUN pip install -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
