FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /
COPY ./requirements.txt /

RUN pip install -r requirements.txt

COPY ./app /app

CMD ["uvicorn", "app.main_api:app", "--host", "0.0.0.0", "--port", "8001"]
