version: '3.8'

services:
  api:
    image: backend_api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://postgres:secrect@142.93.220.56:5432/wwwdb
    networks:
      - app-network

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app-network

  celery_beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app-network

  flower:
    image: mher/flower
    command: flower --port=5555 --broker=redis://redis:6379/0 --basic_auth=user:password
    ports:
      - "5555:5555"
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
