FROM python:3.9

WORKDIR /

# Copy the requirements file
COPY ./requirements.txt /

# Install the dependencies
RUN pip install -r requirements.txt

RUN pip install flower

# Copy the application code
COPY ./app /app

# Expose the Flower port
EXPOSE 5555

# Start Flower
CMD ["celery", "-A", "app.tasks", "flower", "--port=5555", "--basic_auth=user:password"]
