FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /
COPY ./requirements.txt /
COPY ./email_templates /email_templates

RUN pip install -r requirements.txt

COPY ./app /app

CMD ["uvicorn", "app.main_dash:app", "--host", "0.0.0.0", "--port", "8000"]
