"""Add Stripe customer ID

Revision ID: 341f9fbe51c9
Revises: af4dae4d4f75
Create Date: 2024-07-11 21:01:55.221743

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341f9fbe51c9'
down_revision: Union[str, None] = 'af4dae4d4f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
