"""Remove user id from alert

Revision ID: 3afa2ffe2085
Revises: cb90a76d6ef1
Create Date: 2024-08-02 15:53:22.636468

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afa2ffe2085'
down_revision: Union[str, None] = 'cb90a76d6ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_id', 'useralertconfig', type_='unique')
    op.create_unique_constraint('unique_user_project_id', 'useralertconfig', ['user_project_id'])
    op.drop_constraint('useralertconfig_user_id_fkey', 'useralertconfig', type_='foreignkey')
    op.drop_column('useralertconfig', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralertconfig', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('useralertconfig_user_id_fkey', 'useralertconfig', 'user', ['user_id'], ['id'])
    op.drop_constraint('unique_user_project_id', 'useralertconfig', type_='unique')
    op.create_unique_constraint('unique_user_id', 'useralertconfig', ['user_id'])
    # ### end Alembic commands ###
