"""Add 2FA for authentication

Revision ID: 403aebc71870
Revises: 341f9fbe51c9
Create Date: 2024-07-12 09:55:58.726602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '403aebc71870'
down_revision: Union[str, None] = '341f9fbe51c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'two_factor_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
