"""Add alerts tables

Revision ID: 6899faf80a08
Revises: 12552b30f728
Create Date: 2024-08-02 14:48:26.646649

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6899faf80a08'
down_revision: Union[str, None] = '12552b30f728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralertconfig', sa.Column('server_error_threshold', sa.Integer(), nullable=True))
    op.add_column('useralertconfig', sa.Column('slow_threshold_threshold', sa.Integer(), nullable=False))
    op.add_column('useralertconfig', sa.Column('check_interval', sa.Integer(), nullable=False))
    op.add_column('useralertconfig', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.create_unique_constraint('unique_user_id', 'useralertconfig', ['user_id'])
    op.drop_column('useralertconfig', 'client_error_threshold_interval')
    op.drop_column('useralertconfig', 'slow_threshold_interval')
    op.drop_column('useralertconfig', 'notification_interval')
    op.drop_column('useralertconfig', 'server_error_threshold_minutes')
    op.drop_column('useralertconfig', 'server_error_interval')
    op.add_column('useralertnotification', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('useralertnotification', sa.Column('user_alert_notification_email_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('useralertnotification', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('useralertnotification', sa.Column('server_error_threshold', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('server_error_threshold_actual', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('client_error_threshold', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('client_error_threshold_actual', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('slow_threshold', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('slow_threshold_threshold', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('slow_threshold_threshold_actual', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('check_interval', sa.Integer(), nullable=True))
    op.add_column('useralertnotification', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.drop_constraint('useralertnotification_alert_config_id_fkey', 'useralertnotification', type_='foreignkey')
    op.create_foreign_key(None, 'useralertnotification', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'useralertnotification', 'useralertnotificationemail', ['user_alert_notification_email_id'], ['id'])
    op.drop_column('useralertnotification', 'alert_config_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralertnotification', sa.Column('alert_config_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'useralertnotification', type_='foreignkey')
    op.drop_constraint(None, 'useralertnotification', type_='foreignkey')
    op.create_foreign_key('useralertnotification_alert_config_id_fkey', 'useralertnotification', 'useralertconfig', ['alert_config_id'], ['id'])
    op.drop_column('useralertnotification', 'read_at')
    op.drop_column('useralertnotification', 'check_interval')
    op.drop_column('useralertnotification', 'slow_threshold_threshold_actual')
    op.drop_column('useralertnotification', 'slow_threshold_threshold')
    op.drop_column('useralertnotification', 'slow_threshold')
    op.drop_column('useralertnotification', 'client_error_threshold_actual')
    op.drop_column('useralertnotification', 'client_error_threshold')
    op.drop_column('useralertnotification', 'server_error_threshold_actual')
    op.drop_column('useralertnotification', 'server_error_threshold')
    op.drop_column('useralertnotification', 'description')
    op.drop_column('useralertnotification', 'user_alert_notification_email_id')
    op.drop_column('useralertnotification', 'user_id')
    op.add_column('useralertconfig', sa.Column('server_error_interval', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('useralertconfig', sa.Column('server_error_threshold_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('useralertconfig', sa.Column('notification_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('useralertconfig', sa.Column('slow_threshold_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('useralertconfig', sa.Column('client_error_threshold_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_user_id', 'useralertconfig', type_='unique')
    op.drop_column('useralertconfig', 'last_checked')
    op.drop_column('useralertconfig', 'check_interval')
    op.drop_column('useralertconfig', 'slow_threshold_threshold')
    op.drop_column('useralertconfig', 'server_error_threshold')
    # ### end Alembic commands ###
