"""Upgrade uptime monitors

Revision ID: ad1583e44c52
Revises: 403aebc71870
Create Date: 2024-07-18 15:14:08.444570

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1583e44c52'
down_revision: Union[str, None] = '403aebc71870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('apilog', 'user_project_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.add_column('uptimemonitor', sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uptimemonitor', sa.Column('expected_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uptimemonitor', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('uptimemonitor', sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('uptimemonitor', sa.Column('task_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uptimemonitor', 'task_id')
    op.drop_column('uptimemonitor', 'public_url')
    op.drop_column('uptimemonitor', 'is_public')
    op.drop_column('uptimemonitor', 'expected_response')
    op.drop_column('uptimemonitor', 'payload')
    # op.alter_column('apilog', 'user_project_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # ### end Alembic commands ###
