"""Add user agent, other params

Revision ID: af4dae4d4f75
Revises: 
Create Date: 2024-07-10 16:31:24.069161

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4dae4d4f75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apilog', sa.Column('user_agent_browser_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_device_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_device_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('user_agent_device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apilog', sa.Column('is_mobile', sa.Boolean(), nullable=True))
    op.add_column('apilog', sa.Column('is_tablet', sa.Boolean(), nullable=True))
    op.add_column('apilog', sa.Column('is_pc', sa.Boolean(), nullable=True))
    op.add_column('apilog', sa.Column('is_touch_capable', sa.Boolean(), nullable=True))
    op.add_column('apilog', sa.Column('is_bot', sa.Boolean(), nullable=True))
    op.add_column('apilog', sa.Column('response_code_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apilog', 'response_code_text')
    op.drop_column('apilog', 'is_bot')
    op.drop_column('apilog', 'is_touch_capable')
    op.drop_column('apilog', 'is_pc')
    op.drop_column('apilog', 'is_tablet')
    op.drop_column('apilog', 'is_mobile')
    op.drop_column('apilog', 'user_agent_device_model')
    op.drop_column('apilog', 'user_agent_device_brand')
    op.drop_column('apilog', 'user_agent_device_family')
    op.drop_column('apilog', 'user_agent_os_version')
    op.drop_column('apilog', 'user_agent_os_family')
    op.drop_column('apilog', 'user_agent_browser_version')
    op.drop_column('apilog', 'user_agent_browser_family')
    # ### end Alembic commands ###
