"""Use project in alert

Revision ID: cb90a76d6ef1
Revises: 6899faf80a08
Create Date: 2024-08-02 15:50:54.316759

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb90a76d6ef1'
down_revision: Union[str, None] = '6899faf80a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralertconfig', sa.Column('user_project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.alter_column('useralertconfig', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'useralertconfig', 'userproject', ['user_project_id'], ['id'])
    op.add_column('useralertnotification', sa.Column('user_project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('useralertnotification_user_id_fkey', 'useralertnotification', type_='foreignkey')
    op.create_foreign_key(None, 'useralertnotification', 'userproject', ['user_project_id'], ['id'])
    op.drop_column('useralertnotification', 'user_id')
    op.add_column('useralertnotificationemail', sa.Column('user_project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('useralertnotificationemail_user_id_fkey', 'useralertnotificationemail', type_='foreignkey')
    op.create_foreign_key(None, 'useralertnotificationemail', 'userproject', ['user_project_id'], ['id'])
    op.drop_column('useralertnotificationemail', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralertnotificationemail', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'useralertnotificationemail', type_='foreignkey')
    op.create_foreign_key('useralertnotificationemail_user_id_fkey', 'useralertnotificationemail', 'user', ['user_id'], ['id'])
    op.drop_column('useralertnotificationemail', 'user_project_id')
    op.add_column('useralertnotification', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'useralertnotification', type_='foreignkey')
    op.create_foreign_key('useralertnotification_user_id_fkey', 'useralertnotification', 'user', ['user_id'], ['id'])
    op.drop_column('useralertnotification', 'user_project_id')
    op.drop_constraint(None, 'useralertconfig', type_='foreignkey')
    op.alter_column('useralertconfig', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('useralertconfig', 'user_project_id')
    # ### end Alembic commands ###
