"""Remove payment fields for open source

Revision ID: remove_payment_fields
Revises: 341f9fbe51c9
Create Date: 2025-04-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'remove_payment_fields'
down_revision: Union[str, None] = '341f9fbe51c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'monthly_credit_limit')
    op.drop_column('user', 'monthly_credit_usage_crossed')
    op.drop_column('user', 'monthly_credit_limit_reset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('monthly_credit_limit', sa.Integer(), nullable=True, default=20000))
    op.add_column('user', sa.Column('monthly_credit_usage_crossed', sa.Boolean(), nullable=True, default=False))
    op.add_column('user', sa.Column('monthly_credit_limit_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###